spring:
  profiles:
    group:
      "local" : "common, local"
      "dev" : "common, dev"

---

spring:
  config:
    activate:
      on-profile: common
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: root
    password: rootpwd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: postgresql
#    open-in-view: false
    generate-ddl: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      client-id: base-sub-client
      group-id: base-group-1
      auto-offset-reset: latest
    producer:
      bootstrap-servers: localhost:9092
      client-id: base-pub-client


server:
  address: localhost
  port: 7070

---

spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.example.base: info
---

spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    com.example.base: debug

kafka:
  topic:
    sample: spring-boot-sample
    object-sample: spring-boot-sample-object