spring:
  profiles:
    group:
      "local" : "common, local"
      "dev" : "common, dev"

---

spring:
  config:
    activate:
      on-profile: common
  datasource:
    url: jdbc:postgresql://localhost:5432/base
    driver-class-name: org.postgresql.Driver
    username: root
    password: rootpwd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: postgresql
#    open-in-view: false
    generate-ddl: true
  kafka:
    consumer:
      client-id: base-sub-client
      group-id: base-group-1
      auto-offset-reset: latest
    producer:
      client-id: base-pub-client
    bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
    listener:
      ack-mode: manual


server:
  address: localhost
  port: 7070

logging:
  level:
    com:
      example:
        base: debug

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: local

kafka:
  topic:
    object-sample: spring-boot-object-sample
    sample: spring-boot-sample
