spring:
  profiles:
    group:
      "local" : "common, local"
      "dev" : "common, dev"

---

spring:
  config:
    activate:
      on-profile: common
  datasource:
    url: jdbc:postgresql://localhost:5432/base
    driver-class-name: org.postgresql.Driver
    username: root
    password: rootpwd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: postgresql
#    open-in-view: false
    generate-ddl: true


server:
  address: localhost
  port: 7070



---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: local
